name: CI/CD for React UI Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted # RedHat 8 environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        run: |
          curl -sL https://rpm.nodesource.com/setup_18.x |sudo bash -
          sudo dnf install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the React library
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./dist

  dockerize:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker
        run: |
          sudo dnf install -y yum-utils
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo dnf install docker-ce docker-ce-cli containerd.io -y
          sudo systemctl start docker

      - name: Build Docker image
        run: |
          docker build -t aliayman225/react-ui-library:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: |
          docker tag aliayman225/react-ui-library:${{ github.sha }} aliayman225/react-ui-library:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push aliayman225/react-ui-library:${{ github.sha }}
          docker push aliayman225/react-ui-library:latest

