name: CI/CD for React UI Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted # RedHat 8 environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        run: |
          curl -sL https://rpm.nodesource.com/setup_18.x |sudo bash -
          sudo dnf install -y nodejs

      - name: Setup npm authentication
        run: |
	  echo "//localhost:8081/repository/npm-private/:_authToken=32bc3152-8637-3e67-9a03-09dcee450871" > ~/.npmrc



      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true

  build:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup npm authentication
        run: |
	  echo "//localhost:8081/repository/npm-private/:_authToken=32bc3152-8637-3e67-9a03-09dcee450871" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build the React library
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./dist

  publish:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup npm authentication
        run: |
	  echo "//localhost:8081/repository/npm-private/:_authToken=32bc3152-8637-3e67-9a03-09dcee450871" > ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Publish to Nexus
        run: npm publish --registry http://localhost:8081/repository/npm-private/
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

